### ISSUE TITLE
Start.sh IncludeOptional <--- httpd.conf bottom

### ISSUE THREAD

**Issue by cone16** [timtim8461/ish-webserver-setup#3]
Hi, ich weiss is schon etwas älter, ich konnte dein Tool allerdings zum lernen gut brauchen. Wollte mal n issue da lassen und ein Dankeschön. So musste ich mich mit der installiererei nicht rumschlagen.😅

Hi, i know this repository is a bit older, but your tool for me was really usefull to learn. I also would like to thank you, because now i dont need to install all those things by myself. 😅

**Comment by SloppyDE** [comment]
Wie wurde das Problem gelöst?

**Comment by cone16** [comment]
Include (space) Optional. 

nehme mal an ein Tippfehler.
